services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nowo\BeaconBundle\Dsn\BeaconDsnParser: ~

    Nowo\BeaconBundle\Breadcrumb\BreadcrumbBuffer:
        tags:
            - { name: kernel.reset, method: reset }

    Nowo\BeaconBundle\Scope\Scope:
        tags:
            - { name: kernel.reset, method: reset }

    Nowo\BeaconBundle\Instrumentation\SpanBuffer:
        tags:
            - { name: kernel.reset, method: reset }

    Nowo\BeaconBundle\Envelope\PendingTransportRegistry: ~

    Nowo\BeaconBundle\EventListener\BeaconExceptionListener:
        tags:
            - { name: kernel.event_subscriber }

    Nowo\BeaconBundle\EventListener\BeaconConsoleErrorListener:
        tags:
            - { name: kernel.event_subscriber }
